### ISSUE TITLE
Escaping of brackets "(" and ")" in redirect for assets

### ISSUE THREAD

**Issue by GuangHa** [neos/redirecthandler#55]
### Description

Replacing assets in Backend of files with brackets in the filename doesn't do the redirect correctly. I think the problem lies either in the encoding of the sourcepath for inserting into the database table or in the decoding of the redirect.
This is an example on how it is stored in the database:
`_Resources/Persistent/9/0/f/f/90ffd2359008d82298821d16b21778c5c39aec36/Table%20rates%20%28Status%20as%20of%2030%20September%202021%29.pdf`

This is how it tries to find the entry in the database (I think it uses the function `getOneBySourceUriPathAndHost` from `redirectStorage`):
`/_Resources/Persistent/9/0/f/f/90ffd2359008d82298821d16b21778c5c39aec36/Table%20rates%20(Status%20as%20of%2030%20September%202021).pdf`

As you can see the Brackets `()` are either not correctly saved in the database or it is not decoding correctly in the redirect.

### Steps to Reproduce

1. Upload Asset with a filename that contains brackets and open it in a browser (in my case I used a pdf)
2. Use the replace asset function, check both checkboxes (keep filename and do the redirect of the old url)
3. reload the asset in browser (the link to the resource)
4. It loads a 404 site instead of redirecting to the new resource

#### Expected behavior

Loading old resource url should redirect me to the new resource

#### Actual behavior

It leads to a 404

### Affected Versions

Neos: 5.3
Flow: 6.3

**Comment by kdambekalns** [comment]
Might have been solved by https://github.com/neos/redirecthandler/commit/7940cd399461c29d72e12b985791e5d5df86a83b (is in since 5.0.0, 4.0.4)

**Comment by kdambekalns** [comment]
Could it be you run into the "default rewrite rules" trap? See first thing [in the Configuration section](https://github.com/neos/redirecthandler#configuration):

> Note: When using this to handle redirects for persistent resources, you must adjust the default rewrite rules! By default, any miss for _Resources/… stops the request and returns a 404 from the webserver directly:
> […]
> For the redirect handler to even see the request, this has to be removed. Usually the performance impact can be neglected, since Flow is only hit for resources that once existed and to which someone still holds a link.

**Comment by GuangHa** [comment]
Could it be a problem in Firefox with the encoding?

This is before i replaced the file (with keeping the name as is):
![grafik](https://user-images.githubusercontent.com/12826344/142852144-47c79f5d-6bac-42ad-b50d-4c64a1c17e15.png)

After replacing and calling the same url I get a 404-error. If I copy the same url and open it in Chrome the redirect works.

Firefox-Version: 94.0
These are the version of the redirecthandler-packages:
![grafik](https://user-images.githubusercontent.com/12826344/142852709-7fce2fef-16dd-4753-aad2-de54d00ff4ee.png)

**Comment by kdambekalns** [comment]
How do get that URL? And what is actually sent by Firefox (see Network tab in the developer tools) when you open that URL?

I did some more tests, using an image with parentheses in the filename as well as a PDF document linked in the content. This is the source code:

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/95873/142860668-a62f186f-73b8-4381-b2e9-6e457eb137b3.png">
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/95873/142860621-24774a3e-9965-4f79-b690-219c56fe3e00.png">

In Both cases the source code has the correctly encoded parentheses. The same is shown in the web developer tools DOM inspector.

Using "copy (image) link" in Firefox gives me:

- `http://neosdev.localbeach.net/_Resources/Persistent/d/7/5/e/d75ea21c3e85e5d2b828cb5f50e9bf518aa103bc/content-5%20%28copy%29.gif`
- `http://neosdev.localbeach.net/_Resources/Persistent/9/4/f/b/94fb7478941645fba44b4221d8c86409d23e81a6/Beach%20Pakete%20%28und%20Preise%29.pdf`

Now I replaced both fles with something else, creating a redirect and keeping the name.

- The source now has the correctly encoded links pointing to the new resource, as is to be expected.
- The copied links get redirected as expected.
- Clicking the (old) link on the page works as expected.

I cannot reproduce this, and would still assume the redirect handler is not even invoked, because Apache stops handing the request due to the standard rewrite rules being used. The fact this works in Chrome speaks against this. So I tried to manually enter `http://neosdev.localbeach.net/_Resources/Persistent/d/7/5/e/d75ea21c3e85e5d2b828cb5f50e9bf518aa103bc/content-5%20(copy).gif` in Firefox and Chrome. Both resulted in a 404 for me.

**Comment by GuangHa** [comment]
It might be a problem with copying the link. Weirdly when i copied to a new tab in Firefox it uses `...sample (test).pdf` and when i copy it to a chrome tab it uses `...sample%20%28test%29.pdf`. I will check again with our client about this problem and will report back here...if there is no problem anymore I will close this.

**Comment by GuangHa** [comment]
Seems to be solved, I also cannot reproduce it anymore, I will close this issue.
